
NAME := Display.a
FANCY_NAME := Engine/Display

################################################################

DIR_SRC := src/Display/
DIR_OBJ := obj/Display/

################################################################

FILES := \
	AspectRatio.cpp \
	PixelSize.cpp \
	DisplaySize.cpp \
	PixelPosition.cpp \
	DisplayPosition.cpp \
	NormalPosition.cpp \

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/ ../include/ ../ValueType/include/
ARGUMENTS := 

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
