
NAME := Generics.a
FANCY_NAME := Engine/Generics

################################################################

DIR_SRC := src/Generics/
DIR_OBJ := obj/Generics/

################################################################

FILES := \
	Container/Void.cpp \

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/
ARGUMENTS := 

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
