
NAME := Context0.a
FANCY_NAME := Context0

################################################################

FILES := \
	Context0.cpp \
	Context0Menu.cpp \

################################################################

BASE_DIR := ../../
include ../BaseA.mk

################################################################

include $(OTHER_DIR)/UserInterface.mk

include $(REPOS_DIR)/Engine.mk
include $(REPOS_DIR)/FileManager.mk
include $(REPOS_DIR)/OpenGL.mk

################################################################

INCLUDES += . ../
