
NAME := OpenGL.a
FANCY_NAME := Engine/OpenGL

################################################################

DIR_SRC := src/
DIR_OBJ := obj/

################################################################

FILES := \
	OpenGLEnums.cpp \
	OpenGL.cpp \
	../glad/glad.c \

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/
ARGUMENTS := 

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
