
NAME := ValueType.a
FANCY_NAME := Engine/ValueType

################################################################

DIR_SRC := src/ValueType/
DIR_OBJ := obj/ValueType/

################################################################

FILES := \
	Bool/2.cpp \
	Bool/3.cpp \
	Bool/4.cpp \
\
	Vector/F2.cpp \
	Vector/F3.cpp \
	Vector/F4.cpp \
	Vector/U2.cpp \
	Vector/U3.cpp \
	Vector/I2.cpp \
	Vector/I3.cpp \
\
	Box/F1.cpp \
	Box/F2.cpp \
	Box/F3.cpp \
	Box/U2.cpp \
	Box/U3.cpp \
	Box/I2.cpp \
	Box/I3.cpp \
\
	Loop/U2.cpp \
	Loop/U3.cpp \
	Loop/I2.cpp \
	Loop/I3.cpp \
\
	Line/F2.cpp \
	Line/F3.cpp \
\
	Ray/F2.cpp \
	Ray/F3.cpp \
	Ray/Hit/F3.cpp \
\
	Matrix/2x2.cpp \
	Matrix/3x3.cpp \
	Matrix/4x4.cpp \
\
	Trans/2D.cpp \
	Trans/3D.cpp \
\
	Light/Base.cpp \
	Light/Point.cpp \
	Light/Direction.cpp \
	Light/Spot.cpp \
\
	View/2D.cpp \
	View/3D.cpp \
\
	Color/U4.cpp \
	Color/F4.cpp \
\
	Undex.cpp \
	Angle.cpp \
	EulerAngle3D.cpp \
	DepthFactors.cpp \
	Depth.cpp \
	RangeF.cpp \
	LInter.cpp \
	TriangleF3.cpp \
	NormalPlaneF3.cpp \
	InteractF3.cpp \
	Intersect.cpp \
\
	_Show.cpp

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/
ARGUMENTS := 

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
